version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/password  # Default username and password
    ports:
      - "7474:7474"  # HTTP access
      - "7687:7687"  # Bolt protocol access
